name: deploy
on:
  workflow_dispatch:
  schedule:
    # 土曜日 21:00 (JST) は 土曜日 12:00 (UTC)
    # https://time.is/compare/JST/UTC
    # https://crontab.guru/#00_12_*_*_SAT
    - cron: 00 12 * * SAT
  push:
    branches: main
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Deploy
        run: curl -sSf -X POST "${DEPLOY_WEBHOOK_URL}"
        env:
          # https://developers.cloudflare.com/pages/platform/deploy-hooks
          DEPLOY_WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
