name: test
on:
  pull_request:
  workflow_run:
    workflows: deploy
    types: completed
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - if: github.ref_name != github.event.repository.default_branch
        id: set_preview_env
        shell: bash
        run: echo url="https://$(echo "${HEAD_REF:0:28}" | sed 's/[^_0-9a-z]/-/gi;s/-*$//').jwk.pages.dev/" >> "${GITHUB_OUTPUT}"
        env:
          HEAD_REF: ${{ github.head_ref }}
      - name: Run tests on ${{ env.BASE_URL }}
        run: npm test
        env:
          BASE_URL: ${{ github.ref_name == github.event.repository.default_branch && 'https://jwk.pages.dev/' || steps.set_preview_env.outputs.url }}
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: always()
        with:
          name: "playwright-report-${{ matrix.os }}"
          path: playwright-report
